ALTER TABLE users
ALTER COLUMN balance TYPE DOUBLE PRECISION,
ALTER COLUMN withdrawn TYPE BIGINT;

ALTER TABLE withdrawals
ALTER COLUMN sum TYPE BIGINT;

ALTER TABLE orders
ALTER COLUMN accrual TYPE BIGINT;
