CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    login VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    token VARCHAR NOT NULL UNIQUE,
    balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    withdrawn BIGINT NOT NULL DEFAULT 0
);
