ALTER TABLE users
ALTER COLUMN balance TYPE DECIMAL(20, 4),
ALTER COLUMN withdrawn TYPE DECIMAL(20, 4);

ALTER TABLE withdrawals
ALTER COLUMN sum TYPE DECIMAL(20, 4);

ALTER TABLE orders
ALTER COLUMN accrual TYPE DECIMAL(20, 4);
